import { Component } from '@angular/core';
import { LegalLayoutComponent } from './legal-layout.component';

@Component({
  selector: 'app-disclaimer',
  standalone: true,
  imports: [LegalLayoutComponent],
  template: `
    <app-legal-layout
      heading="Disclaimer"
      path="/disclaimer"
      lead="Zenamaze offers guidance, not professional advice."
      updated="July 2, 2026"
      description="Important disclaimer: Zenamaze provides coaching and productivity guidance and is not a substitute for professional, medical, legal or financial advice.">

      <p><strong>Zenamaze</strong> provides goal‑setting and productivity guidance, including suggestions generated by AI. This content is for general informational and motivational purposes only.</p>

      <h2>Not professional advice</h2>
      <p>Zenamaze is <strong>not</strong> a substitute for professional advice. It does not provide medical, psychological, legal, or financial advice. Always consult a qualified professional before making decisions that affect your health, finances, or legal situation.</p>

      <h2>Health &amp; wellbeing</h2>
      <p>If your goals relate to health, fitness, diet, or mental wellbeing, consult a licensed practitioner first. Zenamaze does not diagnose, treat, or cure any condition.</p>

      <h2>Emergencies</h2>
      <p>Zenamaze is not an emergency service. If you are in crisis or experiencing a medical emergency, contact your local emergency number or a qualified professional immediately. Do not rely on Zenamaze reminders or notifications for time‑critical or safety‑critical needs.</p>

      <h2>AI‑generated content</h2>
      <p>Plans and suggestions may be produced by automated systems and can be incomplete or inaccurate. Use your own judgement, and verify anything important.</p>
    </app-legal-layout>
  `,
})
export class DisclaimerComponent {}
